"""Trend review app — approve or reject candidate names generated by the pipeline.

Local:
    .venv/bin/streamlit run review_app.py

Streamlit Community Cloud:
    Deploy this repo. The app reads output/agentic_trends.csv from the repo.
    Changes are held in session state and can be downloaded as a CSV when done.
    Upload the downloaded CSV back to the repo to persist reviews.
"""
from __future__ import annotations

import datetime
import os

import pandas as pd
import streamlit as st

CSV_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output", "agentic_trends.csv")

# Detect whether we can write to disk (local) or must use session state (cloud)
def _is_local() -> bool:
    try:
        with open(CSV_PATH, "a"):
            pass
        return True
    except OSError:
        return False


st.set_page_config(page_title="AJIO Trend Review", layout="wide")


# ── data helpers ─────────────────────────────────────────────────────────────

def _load_from_disk() -> pd.DataFrame:
    df = pd.read_csv(CSV_PATH, dtype=str).fillna("")
    for col in ("review_status", "approved_name", "reviewer", "reviewer_notes", "reviewed_at"):
        if col not in df.columns:
            df[col] = ""
    return df


def _get_df() -> pd.DataFrame:
    """Return working dataframe — from session state (cloud) or disk (local)."""
    if "df" not in st.session_state:
        st.session_state["df"] = _load_from_disk()
    return st.session_state["df"]


def _save_df(df: pd.DataFrame) -> None:
    """Persist dataframe — to disk if local, always keep in session state."""
    st.session_state["df"] = df
    if _is_local():
        df.to_csv(CSV_PATH, index=False)


def _candidates(row: pd.Series) -> list[str]:
    raw = str(row.get("candidate_names", ""))
    return [c.strip() for c in raw.split("|") if c.strip()]


def _badge_color(status: str) -> str:
    return {"approved": "green", "rejected": "red", "pending": "orange"}.get(status, "grey")


# ── sidebar ──────────────────────────────────────────────────────────────────

st.sidebar.title("AJIO Trend Review")
reviewer_name = st.sidebar.text_input("Your name", value="reviewer")

local = _is_local()
if not local:
    st.sidebar.info("Running on cloud — changes are saved in this session. Download the CSV when done.")

df_all = _get_df()

status_filter = st.sidebar.multiselect(
    "Status", ["pending", "approved", "rejected"], default=["pending"],
)
category_filter = st.sidebar.multiselect(
    "Category", sorted(df_all["trend_category"].unique()),
    default=sorted(df_all["trend_category"].unique()),
)
source_filter = st.sidebar.multiselect(
    "Source", sorted(df_all["source"].unique()),
    default=sorted(df_all["source"].unique()),
)

# Download button (always visible on cloud; available locally too)
st.sidebar.divider()
csv_bytes = df_all.to_csv(index=False).encode()
st.sidebar.download_button(
    label="⬇ Download reviewed CSV",
    data=csv_bytes,
    file_name=f"agentic_trends_reviewed_{datetime.date.today()}.csv",
    mime="text/csv",
    help="Download and commit to repo to persist reviews",
)

# Upload to restore a previous session
uploaded = st.sidebar.file_uploader("↑ Upload reviewed CSV to restore", type="csv")
if uploaded:
    restored = pd.read_csv(uploaded, dtype=str).fillna("")
    _save_df(restored)
    st.sidebar.success("Restored!")
    st.rerun()

# ── summary bar ──────────────────────────────────────────────────────────────

st.title("AJIO Trend Review")
df_all = _get_df()
counts = df_all["review_status"].value_counts()
c1, c2, c3, c4 = st.columns(4)
c1.metric("Total", len(df_all))
c2.metric("Pending", int(counts.get("pending", 0)))
c3.metric("Approved", int(counts.get("approved", 0)))
c4.metric("Rejected", int(counts.get("rejected", 0)))
st.divider()

df = df_all[
    df_all["review_status"].isin(status_filter) &
    df_all["trend_category"].isin(category_filter) &
    df_all["source"].isin(source_filter)
].copy()

if df.empty:
    st.info("No trends match the current filters.")
    st.stop()

st.caption(f"Showing {len(df)} of {len(df_all)} trends")

# ── review cards ─────────────────────────────────────────────────────────────

changes: dict[str, dict] = {}

for _, row in df.iterrows():
    tid = row["trend_id"]
    status = row["review_status"] or "pending"
    candidates = _candidates(row)

    with st.expander(
        f"[{row['trend_category']}]  {row['trend_name']}  — :{_badge_color(status)}[{status}]",
        expanded=(status == "pending"),
    ):
        col_left, col_right = st.columns([3, 2])

        with col_left:
            st.markdown(f"**Description:** {row.get('description', '')}")
            st.markdown(f"**Signal:** {row.get('raw_signal', '')}")
            st.markdown(f"**Momentum:** {row.get('momentum_label', '')} — {row.get('momentum_basis', '')}")
            if row.get("validity_window"):
                st.markdown(f"**Valid:** {row['validity_window']}")
            if row.get("buzzword_confidence"):
                st.markdown(
                    f"**Buzzword:** {row.get('buzzword_recency', '')} / "
                    f"{row.get('buzzword_confidence', '')} confidence"
                )
            if row.get("category_context"):
                st.markdown(f"**Category context:** {row['category_context']}")
            if row.get("gtrends_score"):
                st.markdown(
                    f"**Google Trends (IN):** score={row['gtrends_score']}  "
                    f"momentum={row.get('gtrends_momentum', '')}  "
                    f"term=`{row.get('gtrends_term', '')}`"
                )

        with col_right:
            if row.get("judge_recommended"):
                score = row.get("judge_top_score", "")
                status_icon = "✓" if row.get("judge_status") == "ok" else "⚠"
                st.markdown(
                    f"**Judge recommends:** `{row['judge_recommended']}` "
                    f"(score={score}) {status_icon}"
                )
                if row.get("judge_flags"):
                    st.caption(f"Flagged: {row['judge_flags']}")

            st.markdown("**Pick approved name:**")
            options = candidates + ["[custom]", "[reject]"]
            current_approved = row.get("approved_name", "")
            current_status = row.get("review_status", "pending")
            judge_rec = row.get("judge_recommended", "")

            default_idx = 0
            if current_status == "rejected":
                default_idx = options.index("[reject]")
            elif current_approved in candidates:
                default_idx = candidates.index(current_approved)
            elif current_approved:
                default_idx = options.index("[custom]")
            elif judge_rec in candidates:
                default_idx = candidates.index(judge_rec)

            choice = st.radio(
                "Candidates", options,
                index=default_idx,
                key=f"radio_{tid}",
                label_visibility="collapsed",
            )

            custom_name = ""
            if choice == "[custom]":
                custom_name = st.text_input(
                    "Custom name",
                    value=current_approved if current_status == "approved" else "",
                    key=f"custom_{tid}",
                )

            notes = st.text_area(
                "Reviewer notes (optional)", value=row.get("reviewer_notes", ""),
                key=f"notes_{tid}", height=60,
            )

            if st.button("Save", key=f"save_{tid}"):
                if choice == "[reject]":
                    changes[tid] = {
                        "review_status": "rejected",
                        "approved_name": "",
                        "reviewer": reviewer_name,
                        "reviewer_notes": notes,
                        "reviewed_at": datetime.datetime.now().isoformat(timespec="seconds"),
                    }
                elif choice == "[custom]":
                    if custom_name.strip():
                        changes[tid] = {
                            "review_status": "approved",
                            "approved_name": custom_name.strip(),
                            "reviewer": reviewer_name,
                            "reviewer_notes": notes,
                            "reviewed_at": datetime.datetime.now().isoformat(timespec="seconds"),
                        }
                    else:
                        st.warning("Enter a custom name first.")
                else:
                    changes[tid] = {
                        "review_status": "approved",
                        "approved_name": choice,
                        "reviewer": reviewer_name,
                        "reviewer_notes": notes,
                        "reviewed_at": datetime.datetime.now().isoformat(timespec="seconds"),
                    }

# ── apply & persist ──────────────────────────────────────────────────────────

if changes:
    df_all = _get_df()
    for tid, updates in changes.items():
        mask = df_all["trend_id"] == tid
        for col, val in updates.items():
            if col not in df_all.columns:
                df_all[col] = ""
            df_all.loc[mask, col] = val
    _save_df(df_all)
    st.success(f"Saved {len(changes)} change(s)." + ("" if local else " Download CSV to persist."))
    st.rerun()
